<?php

namespace CoreBundle\Entity;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllUserAbove($age = 20)
    {
        return $this->createQueryBuilder('d')
->where('d.isEnabled = :enabled')

->setParameter('enabled', true)

->addOrderBy('d.updatedAt', "DESC")

->addOrderBy('d.id', "DESC")

->setMaxResults($limit);
    }

}
